// V2 — améliorations après test utilisateur
// Extraire/Brouillon deviennent une banque globale d'extraits. Simulation retirée du menu.

const V2_EXCERPTS = [
  {source:"IGAS 2026, synthèse §4",excerpt:"Les Alpes-Maritimes disposent de ressources sanitaires importantes et d’un pôle pédiatrique historiquement implanté. Pourtant, la pluralité d’acteurs publics et privés ne s’est pas traduite par une filière territoriale formalisée : les coopérations restent surtout bilatérales et ponctuelles.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"organisation territoriale",idea:"une offre dense ne garantit pas une filière coordonnée",proof:"ressources élevées mais absence de structuration formalisée",doc:"IGAS §4",place:"I-A / organisation et état des lieux"}},
  {source:"IGAS 2026, synthèse §5",excerpt:"Les urgences pédiatriques constituent le principal point de pression. Elles accueillent des recours justifiés mais aussi des passages évitables, faute d’alternatives territoriales suffisamment visibles et intégrées à la régulation du service d’accès aux soins.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"urgences pédiatriques",idea:"le défaut d’alternatives visibles alimente la saturation des urgences",proof:"passages évitables faute d’alternatives intégrées au SAS",doc:"IGAS §5",place:"I-B / fragilités et risques"}},
  {source:"IGAS 2026, synthèse §5",excerpt:"Les soins critiques pédiatriques dépendent d’un nombre restreint d’équipes expertes. La séparation géographique de certaines spécialités et l’insuffisance de protocoles de flux opposables rendent les transferts plus vulnérables, notamment lors des tensions saisonnières.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"soins critiques",idea:"la concentration des compétences et le manque de protocoles fragilisent la continuité",proof:"dépendance à peu d’équipes et protocoles de flux insuffisants",doc:"IGAS §5",place:"I-B / filières critiques"}},
  {source:"IGAS 2026, synthèse §6",excerpt:"La santé mentale de l’enfant et de l’adolescent constitue le principal facteur de risque à moyen terme. La baisse de la démographie des pédopsychiatres et les délais d’accès à l’offre spécialisée entraînent des reports vers les urgences ou des hospitalisations parfois inadaptées.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"pédopsychiatrie",idea:"la santé mentale constitue un point de rupture majeur de la filière",proof:"baisse des pédopsychiatres et reports vers les urgences",doc:"IGAS §6",place:"I-B / risques"}},
  {source:"IGAS 2026, synthèse §7",excerpt:"La PMI, la santé scolaire et les acteurs médico-sociaux sont encore insuffisamment articulés à la régulation des flux. Pourtant, la prévention primaire et secondaire peut réduire les passages évitables aux urgences et améliorer le repérage précoce.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"prévention",idea:"la prévention est un levier encore sous-intégré au pilotage sanitaire",proof:"PMI et santé scolaire insuffisamment articulées malgré leur potentiel",doc:"IGAS §7",place:"I-B / fragilité ou II-A / levier"}},
  {source:"IGAS 2026, synthèse §8",excerpt:"Le projet régional de santé aborde la gradation des recours pédiatriques de manière générale, sans traduction opérationnelle suffisamment détaillée à l’échelle départementale. La mission recommande donc un schéma départemental explicite, partagé et opposable.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"gradation des recours",idea:"la gradation doit être formalisée à l’échelle départementale",proof:"schéma départemental explicite et opposable recommandé",doc:"IGAS §8",place:"II-A / structuration des parcours"}},
  {source:"IGAS 2026, synthèse §9",excerpt:"La révision du projet médico-soignant partagé du GHT doit inscrire la pédiatrie comme axe stratégique. L’IGAS recommande d’étendre la réflexion au-delà des seuls établissements publics afin de tenir compte des ESPIC et des cliniques présentes sur le territoire.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"gouvernance territoriale",idea:"le projet territorial doit intégrer l’ensemble des acteurs publics et privés",proof:"pédiatrie comme axe stratégique du GHT élargi aux autres acteurs",doc:"IGAS §9",place:"II-B / gouvernance"}},
  {source:"IGAS 2026, synthèse §10",excerpt:"La mission recommande la création d’un second site de réanimation pédiatrique au CHU de Nice, complémentaire de la réanimation polyvalente de Lenval. En chirurgie pédiatrique, elle propose une concentration progressive des activités autour de trois sites au maximum.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"filières critiques",idea:"les compétences rares doivent être concentrées et sécurisées",proof:"second site de réanimation et chirurgie concentrée sur trois sites maximum",doc:"IGAS §10",place:"II-A / sécurisation des filières critiques"}},
  {source:"IGAS 2026, synthèse §11",excerpt:"Une organisation départementale des soins non programmés pédiatriques, adossée au SAS et mobilisant les pédiatres de ville, est présentée comme un levier essentiel. Elle doit associer régulation dédiée, créneaux rapides et information uniforme des familles.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"soins non programmés",idea:"l’offre ambulatoire doit être mobilisée pour réduire le recours par défaut aux urgences",proof:"organisation départementale adossée au SAS avec pédiatres de ville",doc:"IGAS §11",place:"II-A / désaturation des urgences"}},
  {source:"IGAS 2026, synthèse §12",excerpt:"La mission préconise une trajectoire pluriannuelle en santé mentale : renforcement des capacités, circuit de crise pour les adolescents, équipes mobiles et délais maximaux d’accès aux consultations prioritaires. La coordination doit être formalisée dans un protocole opposable.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"santé mentale",idea:"la pédopsychiatrie nécessite une trajectoire pluriannuelle et coordonnée",proof:"circuit de crise, équipes mobiles, délais maximaux et protocole opposable",doc:"IGAS §12",place:"II-A / renforcement de la pédopsychiatrie"}},
  {source:"IGAS 2026, synthèse §13",excerpt:"L’IGAS recommande une instance départementale de pilotage placée sous l’autorité du directeur général de l’ARS. Elle serait dotée d’un tableau de bord consolidé, d’une matrice de risques et de revues régulières de filière.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"pilotage",idea:"la transformation exige une gouvernance départementale dotée d’outils de suivi",proof:"instance ARS, tableau de bord et matrice de risques",doc:"IGAS §13",place:"II-B / pilotage et gouvernance"}},
  {source:"IGAS 2026, p.14",excerpt:"Le département compte 96,2 pédiatres pour 100 000 enfants de moins de 15 ans, soit près de deux fois la moyenne nationale, mais seulement 2,9 pédopsychiatres pour 100 000. La démographie des pédopsychiatres a reculé de 12 % entre 2018 et 2023.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"démographie médicale",idea:"l’abondance globale de pédiatres masque une pénurie en pédopsychiatrie",proof:"2,9 pédopsychiatres pour 100 000 et -12 % en cinq ans",doc:"IGAS p.14",place:"I-B / fragilités"}},
  {source:"IGAS 2026, p.14",excerpt:"Près de 90 % des soins critiques pédiatriques, des urgences spécialisées et de la chirurgie pédiatrique de recours sont assurés par le CHU de Nice et la Fondation Lenval. Cette concentration expose la filière aux tensions de ressources humaines et aux ruptures de continuité.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"concentration de l’offre",idea:"la forte concentration des activités critiques crée une dépendance à deux acteurs",proof:"près de 90 % des activités critiques sur CHU Nice et Lenval",doc:"IGAS p.14",place:"I-B / risque de continuité"}},
  {source:"IGAS 2026, p.14",excerpt:"La fréquentation touristique augmente d’environ 25 % en été. Combinée à la dualité littoral–arrière-pays, cette saisonnalité majore les risques de saturation et les inégalités d’accès aux prises en charge complexes.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"saisonnalité et territoire",idea:"les contraintes géographiques et touristiques aggravent les tensions d’accès",proof:"+25 % de fréquentation touristique en été",doc:"IGAS p.14",place:"I-B / risques territoriaux"}},
  {source:"IGAS 2026, p.15",excerpt:"Le taux de pauvreté du département atteint 16,4 %, et il est nettement plus élevé dans certaines configurations familiales et certains quartiers prioritaires. Ces fragilités sociales doivent orienter la stratégie pédiatrique autant que la seule organisation hospitalière.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"vulnérabilités sociales",idea:"la stratégie pédiatrique doit intégrer les fragilités sociales du territoire",proof:"taux de pauvreté de 16,4 % et concentration dans certains publics",doc:"IGAS p.15",place:"I-A / contexte territorial"}},
  {source:"IGAS 2026, §55",excerpt:"De nombreuses conventions existent entre les acteurs, mais les coopérations demeurent majoritairement bilatérales, ad hoc et insuffisamment intégrées dans une gouvernance partagée. Cette fragmentation limite l’anticipation des tensions et la sécurisation des filières critiques.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"coopération",idea:"la multiplicité des coopérations ne compense pas l’absence de gouvernance commune",proof:"coopérations bilatérales et ad hoc malgré de nombreuses conventions",doc:"IGAS §55",place:"I-B / défaut de coordination"}},
  {source:"IGAS 2026, §57",excerpt:"Il n’existe pas de véritable fonction d’observatoire du système pédiatrique départemental mobilisant de manière centralisée les données disponibles. L’IGAS estime cette centralisation indispensable pour permettre un pilotage proactif par l’ARS et le GHT.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"données et pilotage",idea:"l’absence d’observatoire limite le pilotage anticipateur",proof:"pas de centralisation départementale des données disponibles",doc:"IGAS §57",place:"I-B / limite du pilotage"}},
  {source:"IGAS 2026, §60-61",excerpt:"La réanimation pédiatrique de Lenval est géographiquement séparée de plusieurs spécialités pédiatriques situées au CHU. Pour les prises en charge complexes, l’IGAS considère nécessaire de disposer de deux fonctions de soins critiques pédiatriques à Nice.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"réanimation pédiatrique",idea:"la séparation géographique des spécialités justifie une seconde capacité de soins critiques",proof:"deux fonctions de soins critiques jugées nécessaires à Nice",doc:"IGAS §60-61",place:"II-A / sécurisation des soins critiques"}},
  {source:"IGAS 2026, §70",excerpt:"La mission distingue trois risques systémiques : la soutenabilité, en raison de la pression sur les urgences ; la sécurité et la continuité, du fait des tensions sur les compétences et de la dispersion de certaines activités ; enfin l’iniquité, notamment en santé mentale.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"risques systémiques",idea:"les fragilités de la filière se traduisent par trois risques majeurs",proof:"soutenabilité, sécurité/continuité et iniquité",doc:"IGAS §70",place:"I-B / synthèse des risques"}},
  {source:"IGAS 2026, recommandations",excerpt:"Parmi les recommandations figurent une stratégie d’équité entre littoral et arrière-pays, reposant notamment sur des consultations avancées et la télémédecine. L’objectif est de réduire les délais, renoncements et recours tardifs dans les zones les moins bien desservies.",command:"Présenter l’organisation de la filière pédiatrique, ses fragilités et risques, puis les leviers de structuration et de pilotage.",ans:{theme:"équité territoriale",idea:"les écarts d’accès nécessitent des réponses différenciées selon les territoires",proof:"consultations avancées et télémédecine pour l’arrière-pays",doc:"IGAS recommandations",place:"II-A / équité d’accès"}},

  {source:"HCC 2026, résumé exécutif",excerpt:"Les politiques climatiques territoriales sont portées à la fois par les stratégies de l’État, les collectivités territoriales et de multiples acteurs locaux. Elles s’inscrivent ainsi dans une gouvernance multi-niveaux et interagissent avec de nombreuses politiques sectorielles.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"gouvernance climatique",idea:"l’action climatique territoriale repose sur une gouvernance multi-niveaux complexe",proof:"État, collectivités, acteurs locaux et politiques sectorielles",doc:"HCC 2026",place:"I-A / organisation"}},
  {source:"HCC 2026, résumé exécutif",excerpt:"Le rôle des territoires dans la transition climatique a été progressivement intégré à la planification depuis les années 2000, des premiers plans climat aux PCAET et aux COP régionales. La territorialisation de l’action climatique s’est donc nettement renforcée.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"planification climatique",idea:"la territorialisation s’est progressivement institutionnalisée",proof:"montée en puissance des plans climat, PCAET et COP régionales",doc:"HCC 2026",place:"I-A / évolution de la planification"}},
  {source:"HCC 2026, résumé exécutif",excerpt:"Les investissements annuels des collectivités en faveur de la décarbonation dans les transports, le bâtiment et l’énergie sont évalués à près de 8 milliards d’euros en 2023. Dans le même temps, 5,3 milliards d’euros de dépenses d’investissement défavorables au climat ont été identifiées.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"financement",idea:"l’effort d’investissement climatique coexiste avec des dépenses contradictoires",proof:"8 Md€ favorables contre 5,3 Md€ défavorables",doc:"HCC 2026",place:"I-B / moyens et contradictions"}},
  {source:"HCC 2026, résumé exécutif",excerpt:"Les politiques sectorielles sont pilotées à des échelles différentes : certaines principalement au niveau national, d’autres dans des configurations multi-échelles, d’autres encore à dominante locale. Ces différences peuvent créer des incohérences entre objectifs climatiques et autres politiques publiques.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"cohérence des politiques publiques",idea:"la diversité des échelles de pilotage peut produire des contradictions",proof:"échelles nationales, multi-niveaux et locales parfois discordantes",doc:"HCC 2026",place:"I-B / difficultés de gouvernance"}},
  {source:"HCC 2026, résumé exécutif",excerpt:"Les territoires sont inégalement exposés aux impacts du changement climatique et présentent des vulnérabilités différentes selon leurs caractéristiques géographiques, socio-économiques et institutionnelles. La transition doit donc éviter d’accentuer les inégalités territoriales.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"inégalités territoriales",idea:"l’exposition et la vulnérabilité climatiques varient fortement selon les territoires",proof:"vulnérabilités géographiques, socio-économiques et institutionnelles différenciées",doc:"HCC 2026",place:"I-A / disparités territoriales"}},
  {source:"HCC 2026, résumé exécutif",excerpt:"Les contrats pour la réussite de la transition écologique constituent un outil de mise en œuvre de la planification locale. Toutefois, ils ne sont pas accompagnés de crédits spécifiques et reposent sur la mobilisation de financements existants.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"contractualisation financière",idea:"certains outils de planification ne disposent pas de financements dédiés",proof:"CRTE sans crédits spécifiques",doc:"HCC 2026",place:"I-B / limites des moyens"}},
  {source:"HCC 2026, résumé exécutif",excerpt:"Répondre aux appels à projets nécessite des moyens humains et des compétences spécialisées, aussi bien pour identifier les besoins que pour monter les dossiers juridiques, techniques et financiers. Ces capacités d’ingénierie sont inégalement réparties.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"ingénierie territoriale",idea:"la capacité à mobiliser les financements dépend des compétences disponibles",proof:"besoin de compétences spécialisées pour monter et piloter les projets",doc:"HCC 2026",place:"I-B / moyens humains"}},
  {source:"HCC 2026, chapitre 2.3",excerpt:"Pour s’aligner sur les objectifs climatiques nationaux, les dépenses d’investissement devraient augmenter d’environ 130 % pour le bloc communal, 240 % pour les départements et 80 % pour les régions par rapport au niveau de 2022.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"besoins d’investissement",idea:"les moyens actuels sont très inférieurs aux besoins de la transition",proof:"besoins estimés à +130 %, +240 % et +80 % selon les échelons",doc:"HCC 2026",place:"I-B / insuffisance des moyens"}},
  {source:"HCC 2026, chapitre 2.3",excerpt:"L’instabilité de plusieurs dispositifs d’aides sectorielles nuit aux investissements dans des secteurs comme le logement, l’agriculture ou la forêt. La prévisibilité des ressources constitue donc une condition importante de l’action locale.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"stabilité des financements",idea:"l’instabilité des aides fragilise la programmation des investissements",proof:"dispositifs d’aides sectorielles instables",doc:"HCC 2026",place:"II-A / condition de réussite financière"}},
  {source:"HCC 2026, chapitre 2.3",excerpt:"Les procédures d’accès à certains financements représentent un coût bureaucratique important pour les collectivités. Elles peuvent favoriser les métropoles ou les territoires disposant déjà d’une ingénierie solide, au détriment des petites collectivités.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"accès aux financements",idea:"la complexité administrative renforce les inégalités de capacité entre collectivités",proof:"coût bureaucratique et avantage aux territoires mieux dotés en ingénierie",doc:"HCC 2026",place:"I-B / disparités de mise en œuvre"}},
  {source:"HCC 2026, chapitre 2.3",excerpt:"Les moyens d’ingénierie des collectivités ont progressé mais restent insuffisants. L’offre d’accompagnement demeure dispersée, complexe à mobiliser et inégalement dense sur le territoire.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"ingénierie",idea:"l’accompagnement technique progresse mais reste insuffisant et peu lisible",proof:"offre dispersée, complexe et inégalement répartie",doc:"HCC 2026",place:"I-B / limites opérationnelles"}},
  {source:"HCC 2026, chapitre 2.4",excerpt:"L’évaluation ex post des résultats de l’action climatique territoriale demeure un point faible. Les études consacrées aux résultats concrets et à l’efficacité des politiques locales sont encore rares.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"évaluation",idea:"l’efficacité réelle des politiques climatiques territoriales reste difficile à établir",proof:"évaluations ex post rares",doc:"HCC 2026",place:"I-B / faiblesse du suivi ou II-B selon le plan"}},
  {source:"HCC 2026, chapitre 2.4",excerpt:"Les données disponibles sont nombreuses mais souvent éparses, hétérogènes et peu comparables. Les collectivités expriment le besoin de données complètes, fiables, harmonisées et directement utiles à la décision.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"données et indicateurs",idea:"la profusion de données ne garantit pas un suivi opérationnel",proof:"données nombreuses mais hétérogènes et peu comparables",doc:"HCC 2026",place:"II-B / outils de suivi"}},
  {source:"HCC 2026, planification",excerpt:"En mars 2025, 73 % des EPCI soumis à l’obligation avaient publié leur PCAET de deuxième génération, contre 26 % en avril 2021. Environ 76 % de la population française vit désormais dans un EPCI couvert par un PCAET.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"diffusion de la planification",idea:"la couverture par les PCAET progresse fortement mais reste incomplète",proof:"73 % des EPCI obligés en 2025 contre 26 % en 2021",doc:"HCC 2026",place:"I-A / bilan de la planification"}},
  {source:"HCC 2026, évaluation des plans",excerpt:"Les objectifs des planifications territoriales sont hétérogènes, d’ambition variable et seulement partiellement alignés avec les objectifs nationaux. Les méthodes et hypothèses employées diffèrent également selon les territoires.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"alignement des objectifs",idea:"la planification locale reste hétérogène et imparfaitement alignée sur la stratégie nationale",proof:"objectifs d’ambition variable et méthodes hétérogènes",doc:"HCC 2026",place:"I-B / difficultés de cohérence"}},
  {source:"HCC 2026, COP régionales",excerpt:"Le Haut Conseil pour le climat estime difficile de démontrer l’effet amplificateur des COP régionales sur les exercices de planification territoriale. Les comparaisons sont compliquées par des périmètres et des méthodes différents.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"COP régionales",idea:"l’apport réel des nouveaux dispositifs de coordination reste difficile à mesurer",proof:"effet amplificateur des COP difficile à démontrer",doc:"HCC 2026",place:"I-B / évaluation des dispositifs"}},
  {source:"HCC 2026, adaptation",excerpt:"Les financements mobilisés pour l’adaptation ont augmenté depuis les années 2020 mais restent très inférieurs aux besoins d’une adaptation transformationnelle des territoires. Les besoins dépassent probablement largement les ressources mobilisables localement.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"adaptation climatique",idea:"les financements d’adaptation demeurent très insuffisants au regard des besoins",proof:"moyens actuels loin des besoins d’adaptation transformationnelle",doc:"HCC 2026",place:"I-B / insuffisance financière"}},
  {source:"HCC 2026, conditions de réussite",excerpt:"Une action climatique cohérente suppose une coordination verticale entre l’État et les différents niveaux de collectivités, mais aussi une coopération horizontale entre territoires et acteurs. Cette organisation doit tenir compte de la diversité des situations locales.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"coordination",idea:"la réussite dépend d’une coordination à la fois verticale et horizontale",proof:"coordination État-collectivités et coopération entre territoires et acteurs",doc:"HCC 2026",place:"II-A / gouvernance à renforcer"}},
  {source:"HCC 2026, suivi",excerpt:"Le suivi de la seule évolution des émissions ne suffit pas à attribuer les résultats aux politiques locales. Il importe également de mesurer les réalisations correspondant directement aux compétences des collectivités et la mise en œuvre effective des actions.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"indicateurs de résultat",idea:"le suivi doit distinguer effets globaux et réalisations directement imputables à l’action locale",proof:"suivre la mise en œuvre et les résultats tangibles, pas seulement les émissions",doc:"HCC 2026",place:"II-B / évaluation utile au pilotage"}},
  {source:"HCC 2026, résumé exécutif",excerpt:"La transition climatique est urgente mais ses effets distributifs diffèrent selon les territoires. La stratégie nationale doit tenir compte des disparités d’exposition, de vulnérabilité et de capacités d’action afin de ne pas creuser les inégalités.",command:"Dresser le bilan de la territorialisation des politiques climatiques, présenter les moyens et difficultés de mise en œuvre, puis les conditions de réussite.",ans:{theme:"transition juste",idea:"la politique climatique doit intégrer les disparités territoriales pour éviter d’accroître les inégalités",proof:"exposition, vulnérabilité et capacités d’action différenciées",doc:"HCC 2026",place:"II-A / condition de transition juste"}}
];

const V2_VOCAB = [
  ["Multidimensionnel","Qui comporte plusieurs dimensions ou domaines.","Les inégalités présentent un caractère multidimensionnel.","qualification"],
  ["Structurel","Qui tient à l’organisation profonde et durable d’un système.","Ces difficultés revêtent un caractère structurel.","qualification"],
  ["Conjoncturel","Qui résulte d’une situation temporaire ou d’un contexte particulier.","La hausse observée demeure en partie conjoncturelle.","qualification"],
  ["Transversal","Qui concerne plusieurs secteurs, politiques ou acteurs.","La prévention constitue un enjeu transversal.","qualification"],
  ["Sectoriel","Qui se rapporte à un secteur déterminé de l’action publique.","Les réponses sectorielles demeurent insuffisamment coordonnées.","qualification"],
  ["Systémique","Qui affecte l’ensemble d’un système et ses interactions.","La mission identifie un risque systémique de rupture.","qualification"],
  ["Hétérogène","Composé de situations ou d’éléments très différents.","Les situations territoriales demeurent hétérogènes.","qualification"],
  ["Asymétrique","Marqué par un déséquilibre entre deux situations comparables.","La répartition des responsabilités demeure asymétrique.","qualification"],
  ["Différencié","Adapté à des situations distinctes plutôt qu’appliqué uniformément.","Une réponse différenciée selon les territoires apparaît nécessaire.","qualification"],
  ["Cumulatif","Qui s’ajoute à d’autres effets et en accroît la portée.","Ces facteurs produisent des effets cumulatifs.","qualification"],
  ["Récurrent","Qui se reproduit régulièrement.","Les tensions saisonnières sont récurrentes.","qualification"],
  ["Prégnant","Qui s’impose fortement dans une situation.","Les enjeux de recrutement restent prégnants.","qualification"],
  ["Contrasté","Qui présente des évolutions ou résultats opposés.","Le bilan apparaît contrasté selon les territoires.","qualification"],
  ["Polarisé","Réparti autour de positions ou situations opposées.","Le débat apparaît de plus en plus polarisé.","qualification"],
  ["Tendanciel","Qui correspond à une évolution de fond observée dans le temps.","La baisse tendancielle des effectifs se poursuit.","qualification"],
  ["Marginal","De faible importance quantitative ou périphérique.","Les flux extraterritoriaux demeurent marginaux.","qualification"],
  ["Substantiel","Important par son ampleur ou son contenu.","La réforme entraîne un changement substantiel du dispositif.","qualification"],
  ["Prépondérant","Qui occupe une place dominante.","Le rôle de l’échelon régional demeure prépondérant.","qualification"],
  ["Persistance","Maintien dans le temps d’un phénomène.","La persistance des écarts limite la portée du dispositif.","constat"],
  ["Disparité","Écart notable entre groupes, territoires ou situations.","De fortes disparités territoriales persistent.","constat"],
  ["Déséquilibre","Répartition non équilibrée entre plusieurs éléments.","Un déséquilibre persiste dans la répartition des tâches.","constat"],
  ["Sous-représentation","Présence d’un groupe dans une proportion insuffisante.","Les femmes demeurent sous-représentées dans les fonctions de direction.","constat"],
  ["Surreprésentation","Présence d’un groupe dans une proportion particulièrement élevée.","Les femmes sont surreprésentées dans les emplois à temps partiel.","constat"],
  ["Vulnérabilité","Exposition particulière à un risque ou à une fragilité.","La filière présente une vulnérabilité importante en période de tension.","risques"],
  ["Soutenabilité","Capacité d’une organisation à fonctionner durablement avec ses moyens.","La soutenabilité du dispositif doit être garantie.","risques"],
  ["Résilience","Capacité à absorber une crise et à maintenir le fonctionnement.","Le renforcement de la résilience constitue un objectif prioritaire.","risques"],
  ["Effectivité","Caractère réellement appliqué d’une règle ou d’une politique.","L’enjeu porte désormais sur l’effectivité des mesures adoptées.","évaluation"],
  ["Efficience","Rapport entre les résultats obtenus et les moyens mobilisés.","La réforme vise à améliorer l’efficience de l’action publique.","évaluation"],
  ["Portée","Étendue des effets ou du champ d’application d’une mesure.","La portée de la réforme demeure limitée.","évaluation"],
  ["Incidence","Conséquence ou effet d’un phénomène sur un autre.","Cette évolution a une incidence directe sur l’accès au service.","effets"],
  ["Répercussion","Effet indirect produit par un phénomène.","Ces tensions ont des répercussions sur la continuité du service.","effets"],
  ["Effet d’aubaine","Avantage obtenu sans modifier réellement le comportement attendu.","Le dispositif peut générer des effets d’aubaine.","effets"],
  ["Frein","Facteur qui ralentit ou empêche une évolution.","Le déficit d’ingénierie constitue un frein majeur.","limites"],
  ["Obstacle","Élément qui s’oppose à la mise en œuvre ou à l’atteinte d’un objectif.","La fragmentation institutionnelle constitue un obstacle.","limites"],
  ["Lacune","Absence ou manque dans un dispositif ou une organisation.","Le rapport souligne des lacunes dans le suivi.","limites"],
  ["Point de vigilance","Élément nécessitant une attention particulière.","La santé mentale constitue un point de vigilance majeur.","risques"],
  ["Dégradation","Évolution défavorable d’une situation.","La dégradation de la coopération fragilise le fonctionnement.","évolution"],
  ["Recul","Diminution par rapport à une situation antérieure.","La représentation féminine connaît un recul.","évolution"],
  ["Stagnation","Absence de progression notable.","Les indicateurs traduisent une stagnation des résultats.","évolution"],
  ["Infléchissement","Modification de la direction ou du rythme d’une évolution.","Un infléchissement de la tendance apparaît depuis 2024.","évolution"],
  ["Déploiement","Mise en place progressive et concrète d’un dispositif.","Le déploiement du dispositif se poursuit sur le territoire.","action publique"],
  ["Mise en œuvre","Application concrète d’une décision ou d’une politique.","La mise en œuvre demeure inégale selon les collectivités.","action publique"],
  ["Refonte","Transformation profonde d’un dispositif existant.","Une refonte complète du dispositif est prévue.","action publique"],
  ["Levier","Moyen susceptible de produire ou d’accélérer un changement.","La prévention constitue un levier d’action majeur.","action publique"],
  ["Trajectoire","Évolution programmée dans le temps vers un objectif.","Une trajectoire pluriannuelle de renforcement est recommandée.","action publique"],
  ["Déclinaison","Adaptation opérationnelle d’une orientation générale à un niveau particulier.","La déclinaison départementale demeure insuffisante.","action publique"],
  ["Territorialisation","Adaptation d’une politique nationale aux réalités des territoires.","La territorialisation de la politique reste incomplète.","action publique"],
  ["Gradation","Organisation selon plusieurs niveaux de recours ou d’intensité.","La gradation des recours doit être explicitée.","action publique"],
  ["Articulation","Mise en relation cohérente de plusieurs acteurs ou dispositifs.","L’articulation entre l’hôpital et la ville doit être renforcée.","action publique"],
  ["Contractualisation","Formalisation d’engagements réciproques par contrat ou convention.","La contractualisation permet de rendre les engagements opposables.","action publique"],
  ["Formalisation","Mise par écrit et clarification de pratiques, règles ou responsabilités.","La formalisation des procédures sécurise les parcours.","action publique"],
  ["Mutualisation","Mise en commun de moyens, compétences ou ressources.","La mutualisation des compétences rares est recommandée.","action publique"],
  ["Rationalisation","Réorganisation visant à rendre l’action plus cohérente ou efficiente.","La rationalisation des implantations doit préserver l’accès.","action publique"],
  ["Anticipation","Action de prévoir les évolutions ou risques avant leur survenue.","L’anticipation des tensions saisonnières doit être améliorée.","pilotage"],
  ["Tableau de bord","Ensemble synthétique d’indicateurs servant au pilotage.","Un tableau de bord consolidé doit soutenir la décision.","pilotage"],
  ["Arbitrage","Choix entre plusieurs options ou contraintes concurrentes.","Des arbitrages sont nécessaires entre proximité et concentration.","analyse"],
  ["Complémentarité","Caractère de deux actions ou acteurs qui se complètent.","La complémentarité des acteurs doit être organisée.","analyse"],
  ["Lisibilité","Facilité avec laquelle un dispositif ou un parcours peut être compris.","La lisibilité des parcours demeure insuffisante.","analyse"],
  ["Adéquation","Correspondance entre les besoins et les moyens ou réponses apportés.","L’adéquation entre l’offre et les besoins doit être réévaluée.","analyse"],
  ["Pérennisation","Action consistant à rendre durable un dispositif.","La pérennisation du financement est recommandée.","action publique"],
  ["Consolidation","Renforcement d’un dispositif existant pour le stabiliser.","La consolidation des coopérations constitue une étape nécessaire.","action publique"],
  ["Maillage territorial","Répartition organisée d’une offre ou d’acteurs sur un territoire.","Le maillage territorial doit garantir un accès de proximité.","territoires"],
  ["Infléchir","Modifier progressivement une tendance.","Ces mesures visent à infléchir la hausse des dépenses.","verbes"],
  ["Résorber","Faire disparaître progressivement un écart ou une difficulté.","Le plan vise à résorber les inégalités d’accès.","verbes"],
  ["Atténuer","Réduire l’intensité d’un effet ou d’un risque.","Ces mesures permettent d’atténuer les effets de la crise.","verbes"],
  ["Endiguer","Contenir et freiner fortement la progression d’un phénomène.","Le dispositif cherche à endiguer la hausse des passages évitables.","verbes"],
  ["Pallier","Remédier provisoirement à un manque ; se construit sans « à ».","La mutualisation permet de pallier le manque de compétences.","verbes"],
  ["Remédier","Apporter une réponse à une difficulté ; se construit avec « à ».","La réforme vise à remédier aux insuffisances constatées.","verbes"],
  ["Concourir","Contribuer avec d’autres facteurs à un résultat ; se construit avec « à ».","Ces mesures concourent à l’amélioration du service.","verbes"],
  ["Entraver","Faire obstacle au déroulement ou à l’efficacité d’une action.","La fragmentation peut entraver la coordination.","verbes"],
  ["Compromettre","Mettre en danger la réalisation ou la continuité de quelque chose.","Ces tensions peuvent compromettre la continuité des soins.","verbes"],
  ["Objectiver","Fonder une appréciation sur des données vérifiables.","Le tableau de bord doit objectiver les tensions.","verbes"],
  ["Hiérarchiser","Classer selon l’importance ou la priorité.","La matrice permet de hiérarchiser les risques.","verbes"]
].map(([term,def,answer,category])=>({term,def,answer,category,prompt:`Rédige une phrase de note de synthèse utilisant correctement « ${term} ».`}));

const V2_SOCLE_106 = {
  "Acteurs administratifs":["Administration","Agent public","État","Fonctionnaire","Collectivité territoriale","Contractuel","Établissement public","Administré","EPA / EPIC","Usager","Opérateur de l’État","Public","Autorité administrative indépendante (AAI)","Partenaire","Service déconcentré","Partie prenante","Service public","Acteur"],
  "Mots transversaux":["Enjeu","Réforme","Levier","Simplification","Dispositif","Modernisation","Politique publique","Dématérialisation","Gouvernance","Mutualisation","Pilotage","Accompagnement","Coordination","Expérimentation","Articulation","Évaluation","Stratégie","Indicateur","Orientation","Baromètre","Plan d’action","Feuille de route","Objectif","Diagnostic","Finalité","État des lieux","Mesure"],
  "Verbes administratifs":["Mettre en œuvre","Mobiliser","Renforcer","Coordonner","Favoriser","Adapter","Garantir","Structurer","Assurer","Articuler","Prévenir","Évaluer","Accompagner","Anticiper","Déployer","Rationaliser"],
  "Effets et risques":["Impact","Obstacle","Effet","Point de vigilance","Incidence","Fragilisation","Conséquence","Renforcement","Risque","Amélioration","Opportunité","Dégradation","Frein","Contrainte"],
  "Champs d’action":["Mobilité","Qualité du service","Emploi","Continuité du service public","Formation","Cohésion territoriale","Insertion","Développement durable","Attractivité","Transition écologique","Transition","Transition numérique","Innovation","Accès aux droits","Performance"],
  "Expressions":["Cette mesure vise à…","À cet égard…","Il convient de…","En ce sens…","Cette situation met en évidence…","Dans cette perspective…","Le principal enjeu réside dans…","Afin de…","Cette politique repose sur…","En outre…","Cette évolution conduit à…","Toutefois…","Cette démarche contribue à…","Dès lors…","Il apparaît nécessaire de…","Par conséquent…"]
};

const V2_REWRITE = [
  ["Il y a encore beaucoup d’inégalités dans plein de domaines.","Les inégalités présentent un caractère multidimensionnel et persistent dans plusieurs domaines.","Remplacer « il y a » et « plein de » par un constat synthétique ; « multidimensionnel » regroupe plusieurs domaines."],
  ["Les politiques publiques essayent de lutter contre le problème mais ça ne marche pas assez.","L’action publique s’est renforcée, mais son efficacité demeure limitée.","Éviter « essayent », « ça » et le jugement vague ; distinguer action et efficacité."],
  ["Les femmes sont beaucoup moins dans les postes de direction.","Les femmes demeurent sous-représentées dans les fonctions de direction.","Employer « sous-représentation » pour condenser le constat."],
  ["L’État met petit à petit plusieurs mesures en place.","L’État poursuit le déploiement de plusieurs mesures.","« Déploiement » exprime une mise en place progressive."],
  ["Les acteurs ne travaillent pas assez ensemble.","La coordination entre les acteurs demeure insuffisante.","Transformer la phrase orale en notion administrative."],
  ["Il faut faire travailler l’hôpital et la ville ensemble.","Il apparaît nécessaire de renforcer l’articulation entre l’hôpital et la médecine de ville.","Utiliser une tournure impersonnelle et le terme « articulation »."],
  ["Il y a beaucoup de pédiatres mais presque pas de pédopsychiatres.","L’offre pédiatrique globalement dense contraste avec la faiblesse de la démographie des pédopsychiatres.","Faire apparaître le contraste et qualifier précisément le phénomène."],
  ["Les urgences sont pleines parce que les gens n’ont pas d’autre solution.","Le manque d’alternatives lisibles contribue à la saturation des urgences.","Identifier le lien causal sans formulation familière."],
  ["Les petites collectivités ont du mal à demander les aides.","Les petites collectivités rencontrent davantage de difficultés pour mobiliser les dispositifs de financement.","Remplacer « ont du mal » et préciser l’action concernée."],
  ["Les documents de planification ne vont pas tous dans le même sens.","La cohérence entre les différents documents de planification demeure incomplète.","Nommer l’idée de cohérence plutôt que décrire vaguement."],
  ["Les résultats sont très différents selon les endroits.","Les résultats demeurent contrastés et marqués par de fortes disparités territoriales.","Utiliser « contrasté » et « disparités territoriales »."],
  ["Le manque de personnel peut faire que le service ne fonctionne plus correctement.","Les tensions sur les effectifs fragilisent la continuité du service.","Nommer la cause et l’effet avec des termes administratifs précis."],
  ["Les règles existent mais elles ne sont pas vraiment appliquées.","L’effectivité des règles demeure insuffisante malgré l’existence d’un cadre formel.","« Effectivité » distingue l’existence juridique de l’application réelle."],
  ["Les mesures existent mais on ne sait pas vraiment si elles fonctionnent.","L’efficacité des mesures reste difficile à évaluer.","Éviter « on » et distinguer mise en œuvre et évaluation."],
  ["Il faut prévoir les problèmes avant qu’ils arrivent.","Le pilotage doit permettre d’anticiper les risques.","« Anticiper » et « pilotage » condensent l’idée."],
  ["Les acteurs font chacun leurs trucs dans leur coin.","L’action demeure fragmentée entre des acteurs insuffisamment coordonnés.","Reformuler le registre oral en diagnostic d’organisation."],
  ["Les aides changent tout le temps et ça bloque les projets.","L’instabilité des dispositifs d’aide constitue un frein à la programmation des projets.","Transformer deux constats oraux en lien analytique."],
  ["Les données sont nombreuses mais on ne peut pas bien les comparer.","Les données disponibles restent nombreuses, hétérogènes et peu comparables.","Supprimer « on » et qualifier précisément les données."],
  ["La politique concerne beaucoup de sujets différents.","La politique revêt un caractère transversal et multidimensionnel.","Deux adjectifs de synthèse remplacent une longue énumération."],
  ["Les problèmes ne viennent pas juste d’un accident ou d’une mauvaise année.","Les difficultés observées apparaissent principalement structurelles plutôt que conjoncturelles.","Opposer « structurel » et « conjoncturel » pour qualifier la durée du phénomène."],
  ["Il faudrait que les engagements soient écrits noir sur blanc.","Les engagements doivent être formalisés dans un cadre opposable.","« Formaliser » et « opposable » précisent la nature du besoin."],
  ["Les moyens sont trop faibles pour ce qu’il faudrait faire.","Un décalage important demeure entre les besoins identifiés et les moyens mobilisés.","Formuler le rapport besoins/moyens plutôt qu’un jugement vague."],
  ["Cette mesure aide à améliorer les choses.","Cette mesure contribue à l’amélioration de la qualité du service.","Préciser la contribution et l’objectif."],
  ["Les gens ne savent pas où aller pour être pris en charge.","La lisibilité des parcours demeure insuffisante pour les usagers.","Utiliser « lisibilité des parcours » pour synthétiser le problème."],
  ["Certaines zones sont moins bien servies que d’autres.","Des inégalités territoriales d’accès persistent.","Condenser le constat par la notion d’inégalités territoriales d’accès."],
  ["Il y a un risque que tout se bloque si un acteur important ne peut plus assurer.","La dépendance à un acteur pivot crée un risque systémique de rupture.","Identifier la dépendance et qualifier le risque."],
  ["Les mesures doivent continuer dans le temps et pas s’arrêter après un an.","La pérennisation des mesures constitue une condition de leur efficacité.","Employer « pérennisation » et relier durée et efficacité."],
  ["Il faut réunir les moyens de plusieurs services.","La mutualisation des moyens entre services peut renforcer la capacité d’action.","« Mutualisation » remplace une description longue."],
  ["Les objectifs nationaux ne collent pas toujours à la réalité locale.","La déclinaison territoriale des objectifs nationaux demeure parfois insuffisamment adaptée aux réalités locales.","Employer « déclinaison territoriale » et éviter « coller »."],
  ["Le rapport dit qu’il y a trois gros risques.","Le rapport identifie trois risques majeurs.","Un rapport identifie, relève, souligne ou met en évidence ; éviter « dit »."],
].map(([rough,ref,why])=>({rough,ref,why}));

const V2_SYNTAX_EXTRA = [
  {good:"Ces mesures visent à pallier les insuffisances du dispositif.",bad:"Ces mesures visent à pallier aux insuffisances du dispositif.",why:"« Pallier » est transitif direct : on pallie une difficulté, sans « à »."},
  {good:"Cette réforme vise à remédier aux insuffisances constatées.",bad:"Cette réforme vise à remédier les insuffisances constatées.",why:"« Remédier » se construit avec « à »."},
  {good:"La part des femmes députées a reculé en 2024.",bad:"Le nombre de député femme a reculé en 2024.",why:"On écrit « femmes députées » ou « députées » ; l’accord doit être correct."},
  {good:"Le rapport met en évidence plusieurs fragilités.",bad:"Le rapport appuie sur plusieurs fragilités.",why:"Pour présenter un constat, utiliser « mettre en évidence », « souligner » ou « relever »."},
  {good:"Les femmes travaillent à temps partiel trois fois plus souvent que les hommes.",bad:"Le temps partiel chez les femmes est trois fois plus présent que chez les hommes.",why:"La formulation verbale est plus directe et plus naturelle."},
  {good:"Plusieurs inégalités persistent : écarts salariaux, plafond de verre et précarité.",bad:"Écart salarial, plafond de verre, précarité.",why:"Éviter les suites nominales isolées lorsqu’une phrase claire peut être formulée."},
  {good:"La coordination entre les acteurs demeure insuffisante.",bad:"Les acteurs ne travaillent pas assez bien ensemble.",why:"La première formulation est plus précise et administrative."},
  {good:"La réforme s’inscrit dans une logique de renforcement de la transparence.",bad:"La réforme est dans une logique où on renforce la transparence.",why:"Éviter « on » et les constructions orales ; « s’inscrire dans » est une tournure utile."},
  {good:"Les résultats demeurent contrastés malgré les moyens mobilisés.",bad:"Même avec les moyens, les résultats sont quand même très différents.",why:"Éviter les marqueurs oraux et qualifier précisément le bilan."},
  {good:"Le renforcement de l’ingénierie constitue une condition de réussite.",bad:"Avoir plus d’ingénierie, c’est important pour que ça marche.",why:"La première formulation adopte un registre administratif et identifie la fonction de l’ingénierie."}
];

const V2_TITLE_EXTRA = [
  {weak:"Les problèmes de la santé mentale",issues:["trop vague","aucune dynamique","pas de qualification"],ref:"Une filière de santé mentale fragilisée par la baisse des ressources et l’allongement des délais d’accès"},
  {weak:"Les mesures qui peuvent régler les problèmes",issues:["formulation vague","verbe conjugué","absence de contenu"],ref:"Des leviers de structuration visant à sécuriser les parcours et renforcer le pilotage"},
  {weak:"La situation actuelle n’est pas bonne",issues:["jugement non objectivé","registre oral","aucun thème précis"],ref:"Un fonctionnement encore marqué par des fragilités structurelles et des disparités persistantes"},
  {weak:"Les collectivités font beaucoup de choses pour le climat",issues:["registre courant","imprécision","absence de tension analytique"],ref:"Une action climatique territoriale largement déployée mais inégalement dotée en moyens"},
  {weak:"Les limites de ce qui existe déjà",issues:["trop générique","référent imprécis","aucun enjeu"],ref:"Des dispositifs existants dont l’effectivité et l’évaluation demeurent incomplètes"},
  {weak:"Il faut renforcer la coordination",issues:["titre injonctif","verbe conjugué","ne décrit pas le constat"],ref:"Une coordination interinstitutionnelle à consolider pour améliorer la cohérence de l’action"},
  {weak:"Les moyens pour que ça marche mieux",issues:["registre oral","aucun mot administratif","objectif imprécis"],ref:"Des moyens financiers et d’ingénierie à consolider pour renforcer l’effectivité de la politique"},
  {weak:"Les différences entre les territoires",issues:["titre descriptif mais pauvre","absence de qualification","pas de dynamique"],ref:"Des disparités territoriales persistantes en matière d’exposition, de moyens et de capacité d’action"}
];

const V2_VOCAB_BANK = [...new Map([...VOCAB,...V2_VOCAB].map(v=>[norm(v.term),v])).values()];
const V2_SYNTAX_BANK = [...new Map([...SYNTAX,...V2_SYNTAX_EXTRA].map(v=>[norm(v.good),v])).values()];
const V2_TITLE_BANK = [...new Map([...TITLE_EX,...V2_TITLE_EXTRA].map(v=>[norm(v.weak),v])).values()];

// Retire la simulation du menu : les devoirs complets restent faits hors application.
const v2SimIndex = NAV.findIndex(x=>x[0]==="simulation");
if(v2SimIndex>=0) NAV.splice(v2SimIndex,1);
state.v2DraftIndex=0; state.v2DraftHoles=3; state.v2DraftSeed=0; state.v2RewriteIndex=0; state.v2VocabCategory="Tous";

function v2Current(index){return V2_EXCERPTS[((index%V2_EXCERPTS.length)+V2_EXCERPTS.length)%V2_EXCERPTS.length];}
function v2Shuffle(n,seed){const a=[...Array(n).keys()];let x=(seed+1)*9301+49297;for(let i=n-1;i>0;i--){x=(x*233280+49297)%1000003;const j=x%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function v2Parts(ex){return [["Thème",ex.ans.theme],["Idée",ex.ans.idea],["Preuve forte",ex.ans.proof],["Document",ex.ans.doc],["Place",ex.ans.place]];}
function v2Mask(){return new Set(v2Shuffle(5,state.v2DraftIndex+state.v2DraftSeed*17).slice(0,state.v2DraftHoles));}

// Masque le sélecteur de dossier hors Tableau de bord / Plan : Extraire et Brouillon sont désormais des banques globales.
go = function(page){state.page=page;document.querySelectorAll(".section").forEach(s=>s.classList.toggle("active",s.id===page));document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const item=NAV.find(x=>x[0]===page);$("pageTitle").textContent=item[1];$("pageSubtitle").textContent=item[2];$("datasetSelect").style.display=["dashboard","plan"].includes(page)?"":"none";renderPage(page);};

renderDashboard = function(){const ds=DATASETS[state.ds],pct=stats.attempts?Math.round(stats.correct/stats.attempts*100):0;$("dashboard").innerHTML=`<div class="grid cols3"><div class="card"><div class="tiny">Banque d’extraits</div><div class="kpi">${V2_EXCERPTS.length}</div><p class="muted">Passages contextualisés utilisables dans Extraire et Brouillon.</p></div><div class="card"><div class="tiny">Vocabulaire actif</div><div class="kpi">${V2_VOCAB_BANK.length}</div><p class="muted">Lexique actif + socle administratif minimal de 106 mots/formulations.</p></div><div class="card"><div class="tiny">Réussite estimée</div><div class="kpi">${pct}%</div><p class="muted">${stats.attempts} tentative(s). Indicateur d’entraînement, pas une note.</p></div></div><div class="grid cols2" style="margin-top:16px"><div class="card"><h2>Dossier actif pour le module Plan</h2><div class="quote">${escapeHtml(ds.subject)}</div><p class="source">${escapeHtml(ds.source)}</p></div><div class="card"><h2>Priorités</h2><p><b>Extraire :</b> thème → idée → preuve forte à partir d’un passage suffisamment long.</p><p><b>Brouillon :</b> condenser le même passage en une ligne squelettique, avec 1 à 5 trous.</p><p><b>Plan :</b> croiser plan-type ISP et termes de la commande.</p><p><b>Rédaction :</b> automatiser titres, vocabulaire et syntaxe.</p></div></div>`;};

renderExtract = function(){const ex=v2Current(state.extractIndex);$("extract").innerHTML=`<div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px"><span class="badge">Extrait ${state.extractIndex+1} / ${V2_EXCERPTS.length}</span><button class="btn ghost" onclick="v2PrevExtract()">← Précédent</button><button class="btn ghost" onclick="nextExtract()">Suivant →</button><button class="btn secondary" onclick="v2RandomExtract()">Aléatoire</button></div><div class="grid cols2"><div class="card"><div class="tiny">Mini-commande</div><div class="example">${escapeHtml(ex.command)}</div><div class="quote" style="font-size:15px;line-height:1.7">${escapeHtml(ex.excerpt)}</div><div class="source">${escapeHtml(ex.source)}</div><div class="feedback warn"><b>Repères :</b> de quoi parle le passage ? Que dit-il exactement ? Quel fait, chiffre ou mécanisme le prouve ? À quelle fonction de la commande sert-il ?</div></div><div class="card"><h2>Transforme l’extrait</h2>${[["theme","Thème","santé mentale / financement / gouvernance"],["idea","Idée","une phrase courte qui dit ce que le document affirme"],["proof","Preuve forte","chiffre, fait, mécanisme ou mesure"],["doc","Document","référence courte à retrouver au brouillon"],["place","Place dans le plan","I-A / état des lieux ; II-B / limites"]].map(([id,l,ph])=>`<label>${l}</label><input id="e_${id}" class="input" placeholder="${ph}">`).join("")}<div class="actions"><button class="btn" onclick="checkExtract()">Corriger</button></div><div id="eFeedback"></div></div></div>`;};
checkExtract = function(){const ex=v2Current(state.extractIndex),fields=["theme","idea","proof","doc","place"],labels={theme:"Thème",idea:"Idée",proof:"Preuve forte",doc:"Document",place:"Place dans le plan"};const scores=fields.map(f=>tokenScore($("e_"+f).value,ex.ans[f]));const avg=scores.reduce((a,b)=>a+b,0)/scores.length,ok=avg>=.34;markAttempt("extract",ok);$("eFeedback").innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>Référence possible</b><br>${fields.map(f=>`<b>${labels[f]} :</b> ${escapeHtml(ex.ans[f])}`).join("<br>")}<hr><span class="tiny">Une autre formulation peut être correcte si elle remplit la même fonction.</span></div>`;};
nextExtract = function(){state.extractIndex=(state.extractIndex+1)%V2_EXCERPTS.length;renderExtract();};
function v2PrevExtract(){state.extractIndex=(state.extractIndex-1+V2_EXCERPTS.length)%V2_EXCERPTS.length;renderExtract();}
function v2RandomExtract(){state.extractIndex=Math.floor(Math.random()*V2_EXCERPTS.length);renderExtract();}

renderDraft = function(){const ex=v2Current(state.v2DraftIndex),parts=v2Parts(ex),mask=v2Mask();$("draft").innerHTML=`<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:14px"><span class="badge">Extrait ${state.v2DraftIndex+1} / ${V2_EXCERPTS.length}</span><span class="tiny">Nombre de trous</span><select style="min-width:75px" onchange="v2ChangeHoles(this.value)">${[1,2,3,4,5].map(n=>`<option value="${n}" ${n===state.v2DraftHoles?'selected':''}>${n}</option>`).join("")}</select><button class="btn ghost" onclick="v2NewMask()">Autres trous</button><button class="btn ghost" onclick="v2PrevDraft()">←</button><button class="btn ghost" onclick="v2NextDraft()">→</button><button class="btn secondary" onclick="v2RandomDraft()">Aléatoire</button></div><div class="grid cols2"><div class="card"><div class="tiny">Mini-commande</div><div class="example">${escapeHtml(ex.command)}</div><h2>Extrait à condenser</h2><div class="quote" style="font-size:15px;line-height:1.7">${escapeHtml(ex.excerpt)}</div><div class="source">${escapeHtml(ex.source)}</div><div class="feedback warn"><b>Objectif :</b> conserver assez d’information pour retrouver l’idée au moment du plan, sans réécrire le document.</div></div><div class="card"><h2>Brouillon minimaliste à trous</h2><p class="muted">Avec 5 trous, tu reconstruis toute la ligne sans aide.</p><div style="display:grid;gap:10px">${parts.map((p,i)=>`<div><span class="tiny"><b>${p[0]}</b></span>${mask.has(i)?`<input class="input" id="v2d_${i}" placeholder="${p[0]}">`:`<div class="split-note"><b>${escapeHtml(p[1])}</b></div>`}${i<4?'<div style="text-align:center;color:#264f7a;font-weight:900">↓</div>':''}</div>`).join("")}</div><div class="actions"><button class="btn" onclick="v2CheckDraft()">Corriger</button><button class="btn ghost" onclick="v2NewMask()">Autres trous</button></div><div id="v2dFeedback"></div></div></div>`;};
function v2ChangeHoles(v){state.v2DraftHoles=Number(v);state.v2DraftSeed++;renderDraft();}
function v2NewMask(){state.v2DraftSeed++;renderDraft();}
function v2CheckDraft(){const ex=v2Current(state.v2DraftIndex),parts=v2Parts(ex),mask=v2Mask(),scores=[...mask].map(i=>tokenScore($("v2d_"+i).value,parts[i][1]));const avg=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:1,ok=avg>=.34;markAttempt("draft",ok);$("v2dFeedback").innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>Ligne de référence :</b><br>${parts.map(p=>escapeHtml(p[1])).join(" → ")}<br><span class="tiny">Le but n’est pas de reproduire mot pour mot, mais de conserver la fonction de chaque élément.</span></div>`;}
function v2NextDraft(){state.v2DraftIndex=(state.v2DraftIndex+1)%V2_EXCERPTS.length;state.v2DraftSeed=0;renderDraft();}
function v2PrevDraft(){state.v2DraftIndex=(state.v2DraftIndex-1+V2_EXCERPTS.length)%V2_EXCERPTS.length;state.v2DraftSeed=0;renderDraft();}
function v2RandomDraft(){state.v2DraftIndex=Math.floor(Math.random()*V2_EXCERPTS.length);state.v2DraftSeed=0;renderDraft();}

renderTitles = function(){const ex=V2_TITLE_BANK[state.titleIndex%V2_TITLE_BANK.length];$("titles").innerHTML=`<div class="card"><span class="badge gold">Titre ${state.titleIndex+1} / ${V2_TITLE_BANK.length}</span><div class="quote"><b>${escapeHtml(ex.weak)}</b></div><label>Ta reformulation</label><input id="tInput" class="input" placeholder="Titre objectif, précis, sans jugement prématuré"><div class="actions"><button class="btn" onclick="v2CheckTitle()">Analyser</button><button class="btn ghost" onclick="v2NextTitle()">Suivant</button></div><div id="tFeedback"></div></div>`;};
function v2CheckTitle(){const ex=V2_TITLE_BANK[state.titleIndex%V2_TITLE_BANK.length],u=$("tInput").value,banned=["pas suffisamment","ne sont pas","compliqu","ne marchent pas","pallier aux","ça","il faut"],ok=u.trim().split(/\s+/).length>=5&&!banned.some(x=>norm(u).includes(norm(x)));markAttempt("titles",ok);$("tFeedback").innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>À surveiller :</b> ${ex.issues.join(" ; ")}<br><b>Référence :</b> ${escapeHtml(ex.ref)}</div>`;}
function v2NextTitle(){state.titleIndex=(state.titleIndex+1)%V2_TITLE_BANK.length;renderTitles();}

function v2VocabPool(){return state.v2VocabCategory==="Tous"?V2_VOCAB_BANK:V2_VOCAB_BANK.filter(v=>(v.category||"socle")===state.v2VocabCategory);}
renderVocab = function(){const cats=["Tous",...new Set(V2_VOCAB_BANK.map(v=>v.category||"socle"))],pool=v2VocabPool();if(state.vocabIndex>=pool.length)state.vocabIndex=0;const ex=pool[state.vocabIndex%pool.length],socle=Object.entries(V2_SOCLE_106).map(([c,a])=>`<details style="padding:8px 0;border-top:1px solid #edf1f5"><summary><b>${escapeHtml(c)}</b> <span class="tiny">(${a.length})</span></summary><div class="chips" style="margin-top:8px">${a.map(x=>`<span class="chip">${escapeHtml(x)}</span>`).join("")}</div></details>`).join("");$("vocab").innerHTML=`<div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:14px"><span class="badge">${state.vocabIndex+1} / ${pool.length}</span><select onchange="v2ChangeVocabCategory(this.value)">${cats.map(c=>`<option ${c===state.v2VocabCategory?'selected':''}>${c}</option>`).join("")}</select><button class="btn ghost" onclick="v2PrevVocab()">←</button><button class="btn ghost" onclick="v2NextVocab()">→</button><button class="btn secondary" onclick="v2RandomVocab()">Aléatoire</button></div><div class="grid cols2"><div class="card"><div class="term">${escapeHtml(ex.term)}</div><span class="badge green">${escapeHtml(ex.category||"socle")}</span><p>${escapeHtml(ex.def)}</p><div class="example"><b>Exercice :</b> ${escapeHtml(ex.prompt)}</div></div><div class="card"><h2>Production active</h2><textarea id="v2VInput" placeholder="Écris une phrase courte, neutre et naturelle."></textarea><div class="actions"><button class="btn" onclick="v2CheckVocab()">Corriger</button><button class="btn ghost" onclick="v2NextVocab()">Mot suivant</button></div><div id="v2VFeedback"></div></div></div><div class="card" style="margin-top:16px"><h2>Socle administratif minimal — 106 mots ou formulations</h2><p class="muted">Ouvre une catégorie pour revoir la banque minimale à reconnaître et réutiliser.</p>${socle}</div>`;};
function v2ChangeVocabCategory(c){state.v2VocabCategory=c;state.vocabIndex=0;renderVocab();}
function v2CheckVocab(){const ex=v2VocabPool()[state.vocabIndex%v2VocabPool().length],s=tokenScore($("v2VInput").value,ex.answer),ok=s>.2;markAttempt("vocab",ok);$("v2VFeedback").innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>Phrase modèle :</b> ${escapeHtml(ex.answer)}<br><span class="tiny">Le but est d’utiliser le terme correctement, pas de reproduire le modèle.</span></div>`;}
function v2NextVocab(){const p=v2VocabPool();state.vocabIndex=(state.vocabIndex+1)%p.length;renderVocab();}
function v2PrevVocab(){const p=v2VocabPool();state.vocabIndex=(state.vocabIndex-1+p.length)%p.length;renderVocab();}
function v2RandomVocab(){const p=v2VocabPool();state.vocabIndex=Math.floor(Math.random()*p.length);renderVocab();}

renderSyntax = function(){const ex=V2_SYNTAX_BANK[state.syntaxIndex%V2_SYNTAX_BANK.length],rw=V2_REWRITE[state.v2RewriteIndex%V2_REWRITE.length];let choices=[ex.good,ex.bad];if(state.syntaxIndex%2)choices.reverse();$("syntax").innerHTML=`<div class="grid cols2"><div class="card"><span class="badge">Correction rapide ${state.syntaxIndex+1}/${V2_SYNTAX_BANK.length}</span><h2>Choisis la formulation correcte</h2>${choices.map(x=>`<button class="option" onclick="v2ChooseSyntax(this,${x===ex.good})">${escapeHtml(x)}</button>`).join("")}<div id="sFeedback"></div><div class="actions"><button class="btn ghost" onclick="v2NextSyntax()">Phrase suivante</button></div></div><div class="card"><span class="badge gold">Brouillon → copie ${state.v2RewriteIndex+1}/${V2_REWRITE.length}</span><h2>Réécris la phrase de brouillon</h2><div class="quote">${escapeHtml(rw.rough)}</div><textarea id="v2RwInput" placeholder="Réécris-la en syntaxe claire, neutre et administrative."></textarea><div class="actions"><button class="btn" onclick="v2CheckRewrite()">Corriger ma phrase</button><button class="btn ghost" onclick="v2NextRewrite()">Suivant</button></div><div id="v2RwFeedback"></div></div></div>`;};
function v2ChooseSyntax(el,good){document.querySelectorAll("#syntax .option").forEach(b=>b.disabled=true);el.classList.add(good?"correct":"wrong");const ex=V2_SYNTAX_BANK[state.syntaxIndex%V2_SYNTAX_BANK.length];markAttempt("syntax",good);$("sFeedback").innerHTML=`<div class="feedback ${good?'good':'warn'}"><b>${good?'Correct':'À corriger'}</b><br>${escapeHtml(ex.why)}<br><b>Forme recommandée :</b> ${escapeHtml(ex.good)}</div>`;}
function v2NextSyntax(){state.syntaxIndex=(state.syntaxIndex+1)%V2_SYNTAX_BANK.length;renderSyntax();}
function v2CheckRewrite(){const rw=V2_REWRITE[state.v2RewriteIndex%V2_REWRITE.length],s=tokenScore($("v2RwInput").value,rw.ref),ok=s>.22;stats.rewrite=(stats.rewrite||0)+1;stats.attempts++;if(ok)stats.correct++;saveStats();$("v2RwFeedback").innerHTML=`<div class="feedback ${ok?'good':'warn'}"><b>Modèle :</b> ${escapeHtml(rw.ref)}<br><b>Réflexe :</b> ${escapeHtml(rw.why)}<br><span class="tiny">Une autre phrase peut être tout aussi correcte ; le score ne mesure que la proximité avec le modèle.</span></div>`;}
function v2NextRewrite(){state.v2RewriteIndex=(state.v2RewriteIndex+1)%V2_REWRITE.length;renderSyntax();}

renderProgression = function(){const pct=stats.attempts?Math.round(stats.correct/stats.attempts*100):0,mods=[["Extraire","extract"],["Brouillon","draft"],["Plan","plan"],["Titres","titles"],["Vocabulaire","vocab"],["Syntaxe QCM","syntax"],["Brouillon → copie","rewrite"]];$("progression").innerHTML=`<div class="grid cols3"><div class="card"><div class="tiny">Tentatives</div><div class="kpi">${stats.attempts}</div></div><div class="card"><div class="tiny">Réussites indicatives</div><div class="kpi">${stats.correct}</div></div><div class="card"><div class="tiny">Taux global</div><div class="kpi">${pct}%</div></div></div><div class="card" style="margin-top:16px"><h2>Répartition des entraînements</h2>${mods.map(([l,k])=>`<div class="stage"><span>${l}</span><span class="time">${stats[k]||0} exercice(s)</span></div>`).join("")}</div><div class="card" style="margin-top:16px"><h2>Priorité</h2><p>La chaîne la plus importante reste <b>Extraire → Brouillon → Plan</b>. Le vocabulaire et la syntaxe servent ensuite à rendre la copie plus dense et plus professionnelle.</p></div>`;};
